version: "3.8"
services:
  traefik:
    image: traefik:v2.9.6
    command:
      --providers.docker=true
      --providers.docker.exposedByDefault=false
      --entryPoints.http.address=:80
    networks:
      - traefik-public
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public

  frontend:
    build:
      context: app/frontend/docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./app:/app
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.frontend.rule=Host(`localhost`) || Host(`www.localhost`)
      - traefik.http.routers.frontend.entryPoints=http
      - traefik.http.services.frontend.loadBalancer.server.port=80
      - traefik.http.middlewares.frontend-redirect.redirectRegex.regex=^(https?://)www.localhost/(.*)$$
      - traefik.http.middlewares.frontend-redirect.redirectRegex.replacement=$${1}localhost/$${2}
      - traefik.http.middlewares.frontend-redirect.redirectRegex.permanent=true
      - traefik.http.routers.frontend.middlewares=frontend-redirect

  frontend-php-fpm:
    build:
      context: app/frontend/docker
      dockerfile: development/php-fpm/Dockerfile
    environment:
      TZ: Europe/Moscow
      MAILER_HOST: mailer
      MAILER_PORT: 1025
      MAILER_USER: app
      MAILER_PASSWORD: secret
      MAILER_FROM_EMAIL: mail@app.test
      ADMIN_EMAIL: admin@app.test
      FRONTEND_URL: http://localhost
    volumes:
      - ./app:/app
      - ./data:/app/data

  cp:
    build:
      context: app/backend/docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./app:/app
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.cp.rule=Host(`cp.localhost`)
      - traefik.http.routers.cp.entryPoints=http
      - traefik.http.services.cp.loadBalancer.server.port=80

  cp-php-fpm:
    build:
      context: app/backend/docker
      dockerfile: development/php-fpm/Dockerfile
    environment:
      TZ: Europe/Moscow
      MAILER_HOST: mailer
      MAILER_PORT: 1025
      MAILER_USER: app
      MAILER_PASSWORD: secret
      MAILER_FROM_EMAIL: mail@app.test
      ADMIN_EMAIL: admin@app.test
      FRONTEND_URL: http://cp.localhost
    volumes:
      - ./app:/app
      - ./data:/app/data

  cli-php:
    build:
      context: app/console/docker
      dockerfile: development/php-cli/Dockerfile
    environment:
      TZ: Europe/Moscow
      MAILER_HOST: mailer
      MAILER_PORT: 1025
      MAILER_USER: app
      MAILER_PASSWORD: secret
      MAILER_FROM_EMAIL: mail@app.test
      ADMIN_EMAIL: admin@app.test
      FRONTEND_URL: http://localhost
    volumes:
      - ./app:/app
      - ./data:/app/data

  app-postgres:
    image: postgres:15.1-alpine
    environment:
      TZ: Europe/Moscow
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    volumes:
      - app-postgres:/var/lib/postgresql/data
    ports:
      - "54321:5432"

  manticore:
    image: manticoresearch/manticore
    restart: always
    ports:
      - "9306:9306"
      - "9308:9308"
      - "9312:9312"
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - manticore:/var/lib/manticore
      - manticore:/var/log/manticore
#      - ./manticore/manticore.conf:/etc/manticoresearch/manticore.conf

  mailer:
    image: mailhog/mailhog
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.mailer.rule=Host(`mailer.localhost`)
      - traefik.http.routers.mailer.entryPoints=http
      - traefik.http.services.mailer.loadBalancer.server.port=8025

volumes:
  app-postgres:
  manticore:

networks:
  traefik-public:
    name: traefik-public
